fix: Import error in notificationService
Changed from require('../models') to individual model imports:
- require('../models/userModel')
- require('../models/organizationModel')

Error: Cannot find module '../models'
Fixed: Import specific model files directly